### ISSUE TITLE
Mention services argument in readme

### ISSUE THREAD

**Issue by mroovers** [WeeJeWel/node-google-backup#4]
Hi, would it be an idea to highlight the `--services` argument in the readme? I have modified your Compose example to enable this in Docker, to allow a choice of services to be backed up.

```yaml
services:
    google-backup:
        image: ghcr.io/weejewel/google-backup:latest
        # Choose which services you want to backup (comma separated list): mail,calendar,contacts
        command: [node, ./bin/google-backup.mjs, --services, "mail,calendar,contacts"]
        environment:
            - GOOGLE_BACKUP_USERNAME=john.doe@gmail.com
            - GOOGLE_BACKUP_PASSWORD=abcd efgh ijkl mnop
            - GOOGLE_BACKUP_FILEPATH=/backups
        volumes:
            - ./backups:/backups
```
